version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    restart: on-failure
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=yoctol
      - RABBITMQ_DEFAULT_PASS=yoctol
  postgres:
    image: postgres:10
    container_name: postgres
    restart: on-failure
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  pgadmin4:
    image: dpage/pgadmin4:4.13
    container_name: pgadmin4
    restart: on-failure
    volumes:
      - "pgadmin4-data:/var/lib/pgadmin"
    ports:
      - "7777:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pg@yoctol.com
      - PGADMIN_DEFAULT_PASSWORD=1234
  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: on-failure
    volumes:
      - "mongo-data:/data/db"
    ports:
      - "27017:27017"

volumes:
  rabbitmq-data:
    external:
      name: rabbitmq-data
  pg-data:
    external:
      name: pg-data
  pgadmin4-data:
    external:
      name: pgadmin4-data
  mongo-data:
    external:
      name: mongo-data
