set nocompatible              " be improved, required

call plug#begin('~/.vim/plugged')
    " https://github.com/neoclide/coc.nvim
    Plug 'neoclide/coc.nvim', {'branch': 'release'}

    " 主要功能是相同 project 的 code 在不同 editor 下能夠保持一致
    " 會讀取 .editorconfig
    Plug 'editorconfig/editorconfig-vim'

    " 檢查 eslint 語法
    Plug 'scrooloose/syntastic'

    " https://github.com/preservim/nerdtree
    Plug 'scrooloose/nerdtree'

    " snippet 打縮寫會自動完成 E.g. cl => console.log
    Plug 'SirVer/ultisnips'

    " contains snippets files and used by SirVer/ultisnips
    Plug 'honza/vim-snippets'

    " https://github.com/terryma/vim-multiple-cursors
    " multiple selections
    Plug 'terryma/vim-multiple-cursors'

    " show git diff
    Plug 'airblade/vim-gitgutter'

    " https://github.com/christoomey/vim-system-copy
    " enable to copy something in vim to system clipboard
    Plug 'christoomey/vim-system-copy'

    " https://github.com/scrooloose/nerdcommenter
    Plug 'scrooloose/nerdcommenter'

    " https://black.readthedocs.io/en/stable/integrations/editors.html#vim
    " black for python
    Plug 'psf/black'

    " https://github.com/majutsushi/tagbar
    Plug 'majutsushi/tagbar'

    " https://github.com/ludovicchabant/vim-gutentags
    Plug 'ludovicchabant/vim-gutentags'

    " https://github.com/google/vim-searchindex
    Plug 'google/vim-searchindex'

" All of your Plugins must be added before the following line
call plug#end()

"-------------------------------------------------------------------------------------------

"" file encoding utf-8
set encoding=utf-8

"" 設定 tab 的字元數
set tabstop=4

"" 設定 tab 為空白
set expandtab

"" show line number
set number

"" 設定縮排寬度
set shiftwidth=4

"" 自動縮排 (優於 auto indent)
set smartindent

" 開啟 vim 的智慧大小寫搜尋
set smartcase
set ignorecase

"" 顯示目前的游標位置
set cursorline

"" 進階查詢, 輸入字符後自動尋找, default 會等輸入完
set incsearch

"" 自動註解
set formatoptions+=r

"" 設定一行長度
set textwidth=120

set hlsearch

set noswapfile

"" inoremap只在 insert 模式下生效
"" vnoremap只在 visual 模式下生效
"" nnoremap只在 normal 模式下生效
"" Press F5 to refresh vimrc
nnoremap <F5> :source $MYVIMRC<CR>
"" Press F6 to change hlsearch
nnoremap <F6> :set hlsearch!<CR>
nnoremap <F7> :set paste!<CR>
inoremap <F7> <ESC>:set paste!<CR>i
nnoremap <F9> :NERDTreeToggle<CR>

" replace mark word without overwriting your last yank
vnoremap p "_dP
nnoremap ln :lnext<CR>
nnoremap lp :lprevious<CR>

" Use CTRL-S for saving
noremap <C-S> :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>

"" 把每一行最後的空白在 :w 後自動刪掉
" autocmd BufWritePre * :%s/\s\+$//e


"" enable backspace key under insert mode
"" set backspace=indent,eol,start

"" 顯示右下角設定值
"" set ruler

"" set mouse enable in all mode
"" set mouse=a

"" 語法上色顯示, default on
"" syntax on

"" 命令模式按 Tab 自動補齊
set wildmenu

:inoremap ( ()<Esc>i
:inoremap (<End> (<Esc>i<End>
:inoremap () ()
:inoremap [<CR> [<CR>]<Esc>ko
:inoremap {<CR> {<CR>}<Esc>ko

"" 關掉 scratch 預覽
set completeopt-=preview

"" run :mes then you can debug
" let g:syntastic_debug = 3

"" Suggest
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
" Add full file path to your existing statusline
set statusline+=%F
" let statusline always visible
set laststatus=2
" modified tag
set statusline+=\ %m

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_loc_list_height = 5

let g:syntastic_mode_map = { 'mode': 'passtive',
                           \ 'active_filetypes': ['python'],
                           \ 'passive_filetypes': ['javascript', 'typescript'] }

" ======================= coc.nvim =======================

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
" personally I change to <C-Up> and <C-Down>.
inoremap <silent><expr> <C-Down>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<C-Down>" :
      \ coc#refresh()
inoremap <expr><C-Up> pumvisible() ? "\<C-p>" : "\<C-Up>"


function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" ======================= coc.nvim end =======================

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

" :h UltiSnips-how-snippets-are-loaded
let g:UltiSnipsSnippetDirectories = ['UltiSnips', 'mySnippets']

" close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Switching on spell-checking, To move to a misspelled word, use ']s' and '[s'.
" To mark a word as good and add it to your spellfile, move your cursor to the word and enter 'zg'.
" more http://vimdoc.sourceforge.net/htmldoc/spell.html
setlocal spell
" The following command will let us press CTRL-N or CTRL-P in insert-mode to complete the word we’re typing!
set complete+=kspell

" check one time after 4s of inactivity in normal mode
set autoread
au CursorHold * checktime

" code folding
set foldmethod=indent
set foldlevel=1
set foldnestmax=3
set foldenable!

" https://github.com/terryma/vim-multiple-cursors
" Custom mapping
let g:multi_cursor_select_all_word_key = '<C-a>'
" Default mapping
let g:multi_cursor_next_key            = '<C-n>'
let g:multi_cursor_prev_key            = '<C-p>'
let g:multi_cursor_skip_key            = '<C-x>'
let g:multi_cursor_quit_key            = '<Esc>'

set listchars=tab:→·,trail:·,extends:»,precedes:«
set list

" set updatetime for vim-gitgutter
set updatetime=1000

" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" keep undo history even exit file
" set undofile

" tagbar
autocmd BufEnter * if &filetype == 'python' | call tagbar#autoopen(1)

let g:tagbar_position = 'left'
let g:tagbar_width = 30
let g:tagbar_sort = 0
" https://github.com/majutsushi/tagbar/issues/568
" waiting for https://github.com/majutsushi/tagbar/issues/635
let g:tagbar_use_cache = 0

let g:gutentags_project_root = ['.git']
" let g:gutentags_trace = 1
